spring.application.name=repositoryservice
server.port=8082

spring.data.mongodb.uri=mongodb+srv://12230028gcit_db_user:iIaMZbTcupB5kBOw@cluster0.eclmltd.mongodb.net/NSPS_DB?retryWrites=true&w=majority

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=luwang314@gmail.com
spring.mail.password=dydo vpch uwar goub
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.error.include-message=always

# Security Config
jwt.secret=mysecretkey2026
jwt.expiration=86400000

eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/